# general params
baseURL = 'https://benfeifke.com/'
languageCode = 'en-us'
title = 'Call me Ben'
theme = "cactus"
gravatar = "benfeifke@gmail.com"
googleAnalytics = "G-CXBJ7FZNWP" # or G-XXXXXXXX if you are using Google Analytics v4 (gtag.js)

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
  colortheme = "white"
  description = "Hi there! I'm Ben, and I'm an entrepreneur who's driven by a curiosity to understand and build the world around me.\n \n Currently, I'm Founder and Principal at [Beyond Data Consulting](https://beyonddataconsulting.io/), where our team of Data and AI experts builds custom Data and AI solutions to take your business to the next level. \n\nBook a free consultation here 👉 https://calendly.com/benfeifke. I look forward to meeting you!"
  mainSection = "All Posts"
  mainSectionTitle = "Writings"
  showAllPostsOnHomePage = true
  googleAnalyticsAsync = false
  # postsOnHomePage = 5
  # mathjax = true

[[params.social]]
  name = "email"
  link = "benfeifke@gmail.com" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/benjamin-feifke/"

[[params.social]]
  name = "github"
  link = "https://github.com/bfeif"

[[params.social]]
  name = "youtube"
  link = "https://www.youtube.com/channel/UClsmEGubpjn_oY9N7sjrIbg"

[[params.social]]
  name = "instagram"
  link = "https://www.instagram.com/benfeifke/"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/benfeifke"

[markup.goldmark.renderer]
unsafe= true
