# general params
baseURL = 'https://benfeifke.com/'
languageCode = 'en-us'
title = 'Call me Ben'
theme = "cactus"
gravatar = "benfeifke@gmail.com"
disqusShortname = "benfeifke"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
  colortheme = "white"
  description = "I'm a data scientist, python developer, data science mentor, consultant, and polyglot."
  mainSection = "All Posts"
  mainSectionTitle = "Writings"
  showAllPostsOnHomePage = true
  # postsOnHomePage = 5
  # mathjax = true
  [params.comments]
  enabled = true

[[params.social]]
  name = "github"
  link = "https://github.com/bfeif"

[[params.social]]
  name = "email"
  link = "benfeifke@gmail.com" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/benjamin-feifke/"

[[params.social]]
  name = "youtube"
  link = "https://www.youtube.com/channel/UClsmEGubpjn_oY9N7sjrIbg"

[[params.social]]
  name = "instagram"
  link = "https://www.instagram.com/funkybiff/"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/normanrookwell"
